### ISSUE TITLE
Rubocop configuration doesn't seem to work

### ISSUE THREAD

**Issue by devonpmack** [ruby-syntax-tree/syntax_tree#128]
I added to my `.rubocop.yml` the suggested configuration.

```
inherit_gem:
  rubocop-shopify: rubocop.yml
  shopify-cloud: rubocop.yml
  syntax_tree: config/rubocop.yml
```
 
Even with that it seems I still get Rubocop errors that I have to manually override such as

`Layout/LineEndStringConcatenationIndentation`
`Layout/LineLength`
`Style/BlockDelimiters`
`Style/RegexpLiteral`
`Style/CommandLiteral`
`Style/SymbolLiteral`

I would expect the config to override them for me, but I'm not sure if this was intentional.

**Comment by xeger** [comment]
I saw something similar after upgrading to Rubocop 1.32 -- my suspicion is that some newer cops were introduced that aren't yet in the stree config. I didn't dig deeper because I am also using stree `--plugins` so its default ruleset isn't useful to me.

I ended up disabling the style and layout departments entirely, instead of inheriting from the stree config.

```yaml
Layout:
  Enabled: false
Style:
  Enabled: false
```

This is slightly unsafe since a few "style" cops actually spot functional/behavioral issues, but I deemed the convenience to outweigh the risk.
