### ISSUE TITLE
Bug with passing arguments for non-tty stdin.

### ISSUE THREAD

**Issue by Tseyang** [ruby-syntax-tree/syntax_tree#159]
In https://github.com/ruby-syntax-tree/syntax_tree/pull/152/files#diff-9c0147bbfba8210004d93e758fd167a09f12f0749003f15bd8ea5f41da995f9bR390, I believe the conditional changed from 

`$stdin.tty? || arguments.any?` to `$stdin.tty? && (arguments.any? || options.scripts.any?)`. This seems to alter the conditional to prevent non-tty stdin from using `FileItem` types. Instead you  get the following warning:

```
[warn] stdin
The listed files did not match the expected format.
```

This popped up for me when I tried to upgrade `syntax_tree` and it broke CI checks I had previously setup. 

If this was intentional, is there a better recommended way to run `stree:check` in CI?

**Comment by kddnewton** [comment]
Yeah this broke and then was fixed again. Are you running on the latest version?

**Comment by Tseyang** [comment]
I was updating to `3.6.0`

**Comment by xfalcox** [comment]
Oh, found the same bug in Discourse. Can't update to 3.6.0 because of this 

https://github.com/discourse/discourse-chat/pull/1256

**Comment by davidtaylorhq** [comment]
In case it's useful for anyone else - we unblocked ourselves at Discourse by faking a TTY in GitHub actions:

```yaml
      - name: Syntax Tree
        shell: script -qefc "/bin/bash {0}" /dev/null # fake tty to work around https://github.com/ruby-syntax-tree/syntax_tree/issues/159
        run: bundle exec stree check **/*.rb
```
